# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        npm install && npm run docs:build
    - name: Install SSH key for deploy
      uses: shimataro/ssh-key-action@v1
      with:
        name: id_rsa-deploy
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        known-hosts: ${{ secrets.KNOWN_HOSTS_TEST }}
        config: |                                         # will be appended!
          Host deploy
            HostName 1.15.75.199
            User ubuntu
            IdentityFile ~/.ssh/id_rsa-deploy
    - name: Deploy
      run: |
        rsync -rv $GITHUB_WORKSPACE/dist/ ubuntu@1.15.75.199:/home/ubuntu/sites/blog
